import React from "react";
import { Link } from "react-router-dom";

const Discaimer = () => {
  return (
    <div className="md:w-4/5 mx-auto md:p-16 p-8">
      <h4 className="md:text-3xl md:text-xl text-md text-center uppercase font-medium mb-5">
        NoteGenie.ai Disclaimer
      </h4>
      <p className="text-gray-500 mb-5">
        Thank you for choosing NoteGenie.ai to streamline your note-taking and
        clinical documentation processes. Our primary goal is to enhance your
        productivity and efficiency. However, it is essential to acknowledge
        certain guidelines to ensure a secure and reliable experience:
      </p>

      <ul className="list-decimal text-gray-500 flex flex-col gap-5">
        <li>
          <h6 className="md:text-xl text-md text-black">
            Protection of Personal and Identifiable Information:{" "}
          </h6>
          <p className="mt-2">
            We kindly request that you refrain from entering personal and
            identifiable information about yourself, your clients, or any other
            individuals. Note Genie assumes no responsibility for any privacy
            breaches that may occur due to the inclusion of such sensitive data.
          </p>
        </li>
        <li>
          <h6 className="md:text-xl text-md text-black">
            Accuracy and Validity of Information:
          </h6>
          <p className="mt-2">
            While we strive to provide accurate and reliable information, Note
            Genie cannot be held responsible for any false, exaggerated, or
            misleading information generated through our website or app. Users
            should exercise their own judgment and verify any content before
            relying on it for decision-making purposes.
          </p>
        </li>
        <li>
          <h6 className="md:text-xl text-md text-black">
            Educational and Professional Documentation Purposes Only:
          </h6>
          <p className="mt-2">
            The information provided on NoteGenie.ai is intended solely for
            educational and professional documentation purposes. It is not
            intended to replace or substitute medical or professional advice.
            Always consult with a qualified professional or healthcare provider
            before making any decisions based on information obtained from our
            app or website.
          </p>
        </li>
        <li>
          <h6 className="md:text-xl text-md text-black">User Responsibility:</h6>
          <p className="mt-2">
            By using NoteGenie.ai, you agree to take responsibility for
            approving the final notes generated by the application. It is
            essential to review and verify the accuracy and appropriateness of
            the notes before incorporating them into any professional or
            clinical context.
          </p>
        </li>
      </ul>

      <p className="text-gray-500">
        Please note that by using NoteGenie.ai, you signify your understanding
        and acceptance of these disclaimers. If you do not agree with any of the
        terms stated above, we kindly ask you to refrain from using our
        services. We reserve the right to modify these disclaimers at any time
        without prior notice.
      </p>

      <p className="text-center md:text-xl text-md mt-7">
        Thank you for your cooperation and understanding.
      </p>
      <button className="w-full text-center mt-5">
        <Link
          to={"/"}
          className="w-full text-center text-gray-500 underline hover:text-primary-dark"
        >
          Go Back
        </Link>
      </button>
    </div>
  );
};

export default Discaimer;
